name: spacebook_invaders
version: "0.1.0"
description: space invaders With Friends(tm)
authors:
- Harry Stern <harry.stern@rutgers.edu>
- Wayne Chang <mail@wycd.net>
homepage: https://github.com/boustrophedon/spacebook_invaders
dependencies:
  browser:
  dartemis:
environment:
  sdk: ">=1.2.0"
